import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
// Real PostgreSQL engine, with local stand-ins for Supabase Auth/Storage tables.
// These tests do not assert that live Supabase login or HTTP file upload passed.
const pg=new PGlite();
const admin='11111111-1111-4111-8111-111111111111', outsider='22222222-2222-4222-8222-222222222222';
const a=admin+'/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa.webp',b=admin+'/bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb.webp';
let cat,id,copy,snapshot,payload;
async function role(name,uid=''){await pg.exec(`reset role; set role ${name};`);await pg.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);}
const query=async(sql,params=[])=> (await pg.query(sql,params)).rows;
async function save(value){return (await query('select public.save_product($1::jsonb) id',[JSON.stringify(value)]))[0].id;}
before(async()=>{
 await pg.exec(`create role anon;create role authenticated;create schema auth;create schema storage;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth,storage to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,primary key(bucket_id,name));create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;alter table storage.objects enable row level security;grant select,insert,delete on storage.objects to anon,authenticated;`);
 for(const filename of ['20260911193029_catalog.sql','20260911193032_initial_collection.sql'])await pg.exec(await readFile(new URL('../supabase/migrations/'+filename,import.meta.url),'utf8'));
 await pg.query('insert into auth.users values($1),($2)',[admin,outsider]);await pg.query('insert into public.admin_users(user_id) values($1)',[admin]);
 cat=(await query("select id from public.categories where code='KT4'"))[0].id;
 payload={request_id:'33333333-3333-4333-8333-333333333333',name:'Database test costume',category_id:cat,description:'Stage dance',subcategory:'',price:750,price_type:'Rental',sizes:['M','L'],colors:['Blue'],tags:['stage'],availability:'Available',published:false,featured:false,images:[{path:a,alt:'Front'},{path:b,alt:'Back'}]};
});
after(()=>pg.close());
test('unchanged migrations create six protected tables, 19 categories and 145 IDs',async()=>{
 const rows=await query("select relname,relrowsecurity from pg_class where relnamespace='public'::regnamespace and relname in ('products','categories','settings','admin_users','costume_ids','product_images')");assert.equal(rows.length,6);assert.ok(rows.every(r=>r.relrowsecurity));assert.equal((await query('select count(*)::int n from public.categories'))[0].n,19);assert.equal((await query('select count(*)::int n from public.costume_ids'))[0].n,145);
});
test('anonymous users read shop/categories but cannot save or escalate',async()=>{await role('anon');assert.equal((await query('select count(*)::int n from public.categories'))[0].n,19);assert.equal((await query('select count(*)::int n from public.settings'))[0].n,1);await assert.rejects(()=>save(payload),/permission denied/);await assert.rejects(()=>query('insert into public.admin_users(user_id) values($1)',[outsider]),/permission denied/);});
test('authenticated non-admin is denied product and Storage writes',async()=>{await role('authenticated',outsider);assert.equal((await query('select public.is_admin() allowed'))[0].allowed,false);await assert.rejects(()=>save(payload),/Not authorized/);await assert.rejects(()=>query("insert into storage.objects(bucket_id,name) values('product-images',$1)",[outsider+'/cccccccc-cccc-4ccc-8ccc-cccccccccccc.webp']),/row-level security/);});
test('admin can upload only under own folder and save multiple images atomically',async()=>{await role('authenticated',admin);await assert.rejects(()=>query("insert into storage.objects(bucket_id,name) values('product-images',$1)",[outsider+'/cccccccc-cccc-4ccc-8ccc-cccccccccccc.webp']),/row-level security/);await query("insert into storage.objects(bucket_id,name) values('product-images',$1),('product-images',$2)",[a,b]);id=await save(payload);snapshot=(await query('select * from public.products where id=$1',[id]))[0];assert.equal(snapshot.costume_id,'KT4-01');assert.deepEqual((await query('select path from public.product_images where product_id=$1 order by sort_order',[id])).map(x=>x.path),[a,b]);});
test('draft product and draft images are hidden from public',async()=>{await role('anon');assert.equal((await query('select * from public.products')).length,0);assert.equal((await query('select * from storage.objects')).length,0);});
test('save retries do not allocate duplicate products or IDs',async()=>{await role('authenticated',admin);assert.equal(await save(payload),id);assert.equal((await query('select count(*)::int n from public.products'))[0].n,1);});
test('edit, image ordering and publication update atomically',async()=>{await save({...payload,id,updated_at:snapshot.updated_at,name:'Edited costume',price:875,published:true,images:[{path:b,alt:'Cover'},{path:a,alt:'Back'}]});const current=(await query('select * from public.products where id=$1',[id]))[0];assert.equal(current.price,'875.00');assert.equal(current.slug,snapshot.slug);assert.equal((await query('select path from public.product_images where product_id=$1 order by sort_order',[id]))[0].path,b);});
test('stale edit is rejected; missing image rolls back changes',async()=>{await assert.rejects(()=>save({...payload,id,updated_at:snapshot.updated_at}),/EDIT_CONFLICT/);const current=(await query('select * from public.products where id=$1',[id]))[0];await assert.rejects(()=>save({...payload,id,updated_at:current.updated_at,name:'Should roll back',images:[{path:admin+'/dddddddd-dddd-4ddd-8ddd-dddddddddddd.webp'}]}),/Image missing/);assert.equal((await query('select name from public.products where id=$1',[id]))[0].name,'Edited costume');});
test('public sees published product, reordered images and search document',async()=>{await role('anon');assert.equal((await query('select * from public.products')).length,1);assert.equal((await query('select * from storage.objects')).length,2);assert.equal((await query("select name from public.products where search_document @@ websearch_to_tsquery('simple','edited')"))[0].name,'Edited costume');});
test('quick availability update is visible publicly',async()=>{await role('authenticated',admin);await query("update public.products set availability='Rented' where id=$1",[id]);await role('anon');assert.equal((await query('select availability from public.products where id=$1',[id]))[0].availability,'Rented');});
test('duplicate gets a fresh permanent ID and shares images safely',async()=>{await role('authenticated',admin);copy=await save({...payload,request_id:'44444444-4444-4444-8444-444444444444',name:'Copy',published:false});assert.equal((await query('select costume_id from public.products where id=$1',[copy]))[0].costume_id,'KT4-02');await query('delete from public.products where id=$1',[id]);assert.equal((await query('select * from public.product_images where product_id=$1',[id])).length,0);assert.equal((await query("delete from storage.objects where bucket_id='product-images' returning name")).length,0);});
test('delete final reference allows cleanup; permanent ID is never reused',async()=>{await query('delete from public.products where id=$1',[copy]);assert.equal((await query("delete from storage.objects where bucket_id='product-images' returning name")).length,2);const next=await save({...payload,request_id:'55555555-5555-4555-8555-555555555555',images:[]});assert.equal((await query('select costume_id from public.products where id=$1',[next]))[0].costume_id,'KT4-03');});
test('category management and settings respect existing grants',async()=>{const created=(await query("insert into public.categories(name) values('New collection') returning *"))[0];assert.ok(created.code);await query("update public.categories set name='Updated collection',active=false where id=$1",[created.id]);await assert.rejects(()=>query("update public.categories set code='OTHER' where id=$1",[created.id]),/permission denied/);await query("update public.settings set description='Updated shop' where id=true");await role('anon');assert.equal((await query('select * from public.categories where id=$1',[created.id])).length,0);assert.equal((await query('select description from public.settings'))[0].description,'Updated shop');});
