import { categories, products, product, settings, watchChanges, money, failure, states } from './api';
import { renderShop } from './shop';
import defaults from './default-shop.json';
import './public-extra.css';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const grid=document.querySelector('#products'),nav=document.querySelector('#categories');
let active='',page=0,cats=[],filter={},generation=0,openSlug=null,detailGeneration=0;
const isDetail=location.pathname.startsWith('/catalog/');
renderShop({...defaults,demo:false});
async function refreshShop(){try{const s=await settings(true);renderShop({brand:s.business_name,demo:false,shop:{...s,owner:s.owner_name,mapsUrl:s.maps_url}});}catch(e){if(!grid)showError(e);}}
function showError(e){let n=document.querySelector('#connection-error');if(!n){n=el('p','catalog-error');n.id='connection-error';n.role='alert';(grid?.parentElement||document.querySelector('main')).prepend(n);}n.textContent='Unable to load the latest catalogue. '+failure(e);}
function photo(holder,p,index=0){holder.replaceChildren();const image=p.images[index];holder.classList.toggle('awaiting-photo',!image?.url);if(!image?.url){holder.append(el('span','placeholder-code',p.costume_id),el('span','placeholder-label','Photo unavailable'));return;}const img=el('img');img.src=image.url;img.alt=image.alt||p.name;img.width=768;img.height=1024;img.loading='lazy';img.onerror=()=>{holder.replaceChildren(el('span','placeholder-label','Photo unavailable'));holder.classList.add('awaiting-photo');};holder.append(img);}
function categoryButton(c){const b=el('button','category-button');b.type='button';b.setAttribute('aria-pressed',String(active===(c?.id||'')));const label=el('span','category-label');label.append(el('span','',c?.name||'All categories'));if(c)label.append(el('small','',c.code+(c.age?' · '+c.age:'')));b.append(label);b.onclick=()=>{active=c?.id||'';page=0;renderNav();void render();};return b;}
function renderNav(){nav.replaceChildren(categoryButton(null));let group='';for(const c of cats){if(group!==c.group_name){group=c.group_name;nav.append(el('p','category-group-label',group));}nav.append(categoryButton(c));}}
function filters(){const box=el('form','catalog-filters');box.setAttribute('aria-label','Search and filter costumes');
 const field=(label,name,type='text')=>{const l=el('label','',label),i=el('input');i.type=type;i.name=name;if(type==='number'){i.min='0';i.step='0.01';}l.append(i);box.append(l);return i;};
 field('Search name, ID or tag','search').placeholder='Find a costume…';
 const select=(label,name,options)=>{const l=el('label','',label),s=el('select');s.name=name;for(const [value,text] of options){const o=el('option','',text);o.value=value;s.append(o);}l.append(s);box.append(l);};
 select('Availability','availability',[['','All statuses'],...states.map(x=>[x,x])]);select('Sort','sort',[['new','Newest'],['name','Name'],['price-up','Price: low to high'],['price-down','Price: high to low']]);
 field('Minimum ₹','min','number');field('Maximum ₹','max','number');field('Size','size').placeholder='e.g. M';field('Colour','color').placeholder='e.g. Blue';
 const apply=el('button','','Apply filters');apply.type='submit';const reset=el('button','','Reset');reset.type='reset';box.append(apply,reset);
 box.onsubmit=e=>{e.preventDefault();filter=Object.fromEntries(new FormData(box));page=0;void render();};box.onreset=()=>{filter={};active='';page=0;renderNav();void render();};
 document.querySelector('.results-header').after(box);
}
async function render(){const version=++generation;document.querySelector('#connection-error')?.remove();const overview=!active&&!Object.values(filter).some(Boolean);
 if(overview){grid.className='category-overview';grid.replaceChildren();document.querySelector('#result-count').textContent=cats.length+' categories';document.querySelector('#empty').hidden=!!cats.length;document.querySelector('#pagination')?.remove();
 for(const c of cats){const b=el('button','category-tile');b.type='button';b.append(el('span','tile-code',String(c.sort_order).padStart(2,'0')+' / '+c.code),el('h3','',c.name),el('p','tile-age',c.age||c.group_name),el('p','tile-range',c.description||'Explore the collection'),el('span','tile-bottom','View collection ↗'));b.onclick=()=>{active=c.id;page=0;renderNav();void render();};grid.append(b);}return;}
 try{const result=await products({...filter,category:active,page},true);if(version!==generation)return;
 if(page>0&&!result.items.length){page--;return render();}
 grid.className='product-grid';grid.replaceChildren();document.querySelector('#result-count').textContent=result.count+' costumes';document.querySelector('#empty').hidden=result.count>0;
 for(const p of result.items){const card=el('article','product-card'),link=el('a','product-open');link.href='/catalog/'+encodeURIComponent(p.slug);link.setAttribute('aria-label','View '+p.costume_id+' '+p.name);const holder=el('div','product-photo');photo(holder,p);const copy=el('div','product-copy');copy.append(el('p','product-code',p.costume_id),el('h3','',p.name));const bottom=el('div','product-bottom'),price=el('p','product-price');price.append(el('span','',p.price_type==='Purchase'?'MRP ':'RENT '),document.createTextNode(money(p)));bottom.append(price,el('span','card-arrow','↗'));copy.append(bottom,el('p','entry-availability',p.availability));link.append(holder,copy);card.append(link);grid.append(card);}
 document.querySelector('#pagination')?.remove();if(result.count>24){const paging=el('div','catalog-pagination');paging.id='pagination';for(const [label,delta,disabled]of [['Previous',-1,page===0],['Next',1,(page+1)*24>=result.count]]){const b=el('button','',label);b.disabled=disabled;b.onclick=()=>{page+=delta;void render();};paging.append(b);}paging.append(el('span','',`Page ${page+1} of ${Math.ceil(result.count/24)}`));grid.after(paging);}
 }catch(e){if(version===generation)showError(e);}}
async function detail(){const version=++detailGeneration;try{const p=await product(decodeURIComponent(location.pathname.split('/')[2]||''),true,true);if(version!==detailGeneration)return;const main=document.querySelector('main');if(!p){main.replaceChildren(el('h1','','Costume unavailable'),el('p','','This costume may have been removed or is no longer published.'));const a=el('a','','Browse the catalogue');a.href='/';main.append(a);return;}
 document.title=p.name+' — Mahakal Drapery';const wrap=el('section','detail-page');const back=el('a','','← Back to catalogue');back.href='/#collection';wrap.append(back);const layout=el('div','detail-layout'),gallery=el('div',''),holder=el('div','detail-photo');photo(holder,p);gallery.append(holder);const thumbs=el('div','detail-thumbnails');p.images.forEach((image,i)=>{const b=el('button');b.type='button';b.setAttribute('aria-label',`View image ${i+1}`);const img=el('img');if(image.url)img.src=image.url;img.alt=image.alt||p.name;b.append(img);b.onclick=()=>photo(holder,p,i);thumbs.append(b);});gallery.append(thumbs);const copy=el('div','detail-copy');copy.append(el('p','eyebrow',p.category.name),el('h1','',p.name),el('p','detail-code','COSTUME ID: '+p.costume_id),el('p','detail-price',money(p)),el('p','detail-description',p.description));const specs=el('dl');for(const [key,value]of [['Age',p.category.age||'Ask the shop'],['Sizes',p.sizes.join(', ')||'Ask the shop'],['Colours',p.colors.join(', ')||'Ask the shop'],['Availability',p.availability]]){const row=el('div');row.append(el('dt','',key),el('dd','',value));specs.append(row);}copy.append(specs,el('p','detail-disclaimer','Please call the shop to confirm rental duration, charges and availability.'));const contact=el('a','detail-contact','Contact the shop ↗');contact.href='/contact.html';copy.append(contact);layout.append(gallery,copy);wrap.append(layout);main.replaceChildren(wrap);
 }catch(e){showError(e);}}
async function refresh(){await refreshShop();if(isDetail)return detail();if(!grid)return;try{cats=await categories(true);if(active&&!cats.some(c=>c.id===active))active='';renderNav();await render();}catch(e){showError(e);}}
if(grid&&!isDetail){filters();document.querySelector('.catalogue-notice').textContent='Browse the collection and quote the costume ID when contacting the shop.';}
void refresh();try{watchChanges(()=>void refresh(),true);}catch(e){showError(e);}
